name: mariosocratesphotography
favicon: null
layout_spectrum: 0.2717857910320163
typography_spectrum: 0.18521219585090876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43970724754035473
  lightness: 0.6397739539388567
  saturation: 0.6490882153157145
  rhythmicContrast: 0.7874213284812868
purpose: []
