name: mariosocratesphotography
favicon: null
layout_spectrum: 0.2717857910320163
typography_spectrum: 0.18521219585090876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3e3e3e'
    - '#868686'
    - '#656565'
    - '#dadada'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
